version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular-devkit/architect"
    versions:
    - 0.1102.10
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: "@angular/cli"
    versions:
    - 11.2.10
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.10
    - 0.1102.7
    - 0.1102.8
    - 0.1102.9
  - dependency-name: "@angular-eslint/schematics"
    versions:
    - 2.1.0
    - 4.0.0
  - dependency-name: "@angular-eslint/template-parser"
    versions:
    - 2.1.0
    - 4.0.0
  - dependency-name: "@angular-eslint/eslint-plugin"
    versions:
    - 1.2.0
    - 2.0.0
    - 2.0.2
    - 2.1.0
    - 4.0.0
  - dependency-name: "@angular-devkit/core"
    versions:
    - 11.2.10
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/language-service"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.8
    - 11.2.9
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@angular-eslint/eslint-plugin-template"
    versions:
    - 1.2.0
    - 2.0.2
    - 2.1.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.21.0
  - dependency-name: tslib
    versions:
    - 2.2.0
  - dependency-name: typedoc
    versions:
    - 0.20.19
    - 0.20.20
    - 0.20.23
    - 0.20.24
    - 0.20.25
    - 0.20.27
    - 0.20.28
    - 0.20.35
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@material/top-app-bar"
    versions:
    - 10.0.0
  - dependency-name: simple-git
    versions:
    - 2.35.2
    - 2.36.0
    - 2.36.1
    - 2.36.2
    - 2.37.0
  - dependency-name: eslint-plugin-prefer-arrow
    versions:
    - 1.2.3
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.4
    - 3.6.6
    - 3.6.7
    - 3.6.8
    - 3.6.9
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@material/layout-grid"
    versions:
    - 10.0.0
  - dependency-name: "@angular-devkit/build-ng-packagr"
    versions:
    - 0.1002.0
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.4.0
    - 31.6.0
    - 31.6.1
    - 32.0.0
    - 32.0.1
    - 32.0.2
    - 32.1.0
    - 32.1.1
    - 32.2.0
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.6
  - dependency-name: "@typescript-eslint/eslint-plugin-tslint"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: bl
    versions:
    - 1.2.3
